# Generated by Django 5.2.1 on 2025-05-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('icon', models.FileField(blank=True, null=True, upload_to='prestation_icon')),
            ],
        ),
    ]
