# Generated by Django 5.2.1 on 2025-05-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestations',
            new_name='Prestation',
        ),
    ]
